
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase GUI ParkingMachine - Examen Final POO I 2017-I.
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
public class ParkingMachine extends javax.swing.JFrame {

    private Parqueadero parqueadero;
    private JLabel[] lblLugarParqueo;
    private JLabel[] lblPosicion;

    DecimalFormat f = new DecimalFormat("###.##");

    /**
     * Creates new form CoffeeMachineView
     */
    public ParkingMachine() {
        parqueadero = new Parqueadero();
        initComponents();
        lblLugarParqueo = new JLabel[]{lblPlaca1, lblPlaca2, lblPlaca3, lblPlaca4, lblPlaca5,
            lblPlaca6, lblPlaca7, lblPlaca8, lblPlaca9, lblPlaca10,
            lblPlaca11, lblPlaca12, lblPlaca13, lblPlaca14, lblPlaca15,
            lblPlaca16, lblPlaca17, lblPlaca18, lblPlaca19, lblPlaca20,
            lblPlaca21, lblPlaca22, lblPlaca23, lblPlaca24, lblPlaca25,
            lblPlaca26, lblPlaca27, lblPlaca28, lblPlaca29, lblPlaca30};
        lblPosicion = new JLabel[]{lblPos1, lblPos2, lblPos3, lblPos4, lblPos5,
            lblPos6, lblPos7, lblPos8, lblPos9, lblPos10,
            lblPos11, lblPos12, lblPos13, lblPos14, lblPos15,
            lblPos16, lblPos17, lblPos18, lblPos19, lblPos20,
            lblPos21, lblPos22, lblPos23, lblPos24, lblPos25,
            lblPos26, lblPos27, lblPos28, lblPos29, lblPos30};
        crearListener();
        actualizarGUI();
    }

    private void crearListener() {
        ParkingLabelListener tmp = null;
        for (int i = 0; i < lblLugarParqueo.length; i++) {
            tmp = new ParkingLabelListener(i);
            lblLugarParqueo[i].addMouseListener(tmp);
            lblPosicion[i].addMouseListener(tmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdgTipoVehiculo = new javax.swing.ButtonGroup();
        lblImagen = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        tabsDatos = new javax.swing.JTabbedPane();
        panelCuadricula = new javax.swing.JPanel();
        lblPos1 = new javax.swing.JLabel();
        lblPlaca1 = new javax.swing.JLabel();
        lblPos2 = new javax.swing.JLabel();
        lblPlaca2 = new javax.swing.JLabel();
        lblPos3 = new javax.swing.JLabel();
        lblPlaca3 = new javax.swing.JLabel();
        lblPos4 = new javax.swing.JLabel();
        lblPlaca4 = new javax.swing.JLabel();
        lblPos5 = new javax.swing.JLabel();
        lblPlaca5 = new javax.swing.JLabel();
        lblPos6 = new javax.swing.JLabel();
        lblPlaca6 = new javax.swing.JLabel();
        lblPos7 = new javax.swing.JLabel();
        lblPlaca7 = new javax.swing.JLabel();
        lblPos8 = new javax.swing.JLabel();
        lblPlaca8 = new javax.swing.JLabel();
        lblPos9 = new javax.swing.JLabel();
        lblPlaca9 = new javax.swing.JLabel();
        lblPos10 = new javax.swing.JLabel();
        lblPlaca10 = new javax.swing.JLabel();
        lblPos11 = new javax.swing.JLabel();
        lblPlaca11 = new javax.swing.JLabel();
        lblPos12 = new javax.swing.JLabel();
        lblPlaca12 = new javax.swing.JLabel();
        lblPos13 = new javax.swing.JLabel();
        lblPlaca13 = new javax.swing.JLabel();
        lblPos14 = new javax.swing.JLabel();
        lblPlaca14 = new javax.swing.JLabel();
        lblPos15 = new javax.swing.JLabel();
        lblPlaca15 = new javax.swing.JLabel();
        lblPos16 = new javax.swing.JLabel();
        lblPlaca16 = new javax.swing.JLabel();
        lblPos17 = new javax.swing.JLabel();
        lblPlaca17 = new javax.swing.JLabel();
        lblPos18 = new javax.swing.JLabel();
        lblPlaca18 = new javax.swing.JLabel();
        lblPos19 = new javax.swing.JLabel();
        lblPlaca19 = new javax.swing.JLabel();
        lblPos20 = new javax.swing.JLabel();
        lblPlaca20 = new javax.swing.JLabel();
        lblPos21 = new javax.swing.JLabel();
        lblPlaca21 = new javax.swing.JLabel();
        lblPos22 = new javax.swing.JLabel();
        lblPlaca22 = new javax.swing.JLabel();
        lblPos23 = new javax.swing.JLabel();
        lblPlaca23 = new javax.swing.JLabel();
        lblPos24 = new javax.swing.JLabel();
        lblPlaca24 = new javax.swing.JLabel();
        lblPos25 = new javax.swing.JLabel();
        lblPlaca25 = new javax.swing.JLabel();
        lblPos26 = new javax.swing.JLabel();
        lblPlaca26 = new javax.swing.JLabel();
        lblPos27 = new javax.swing.JLabel();
        lblPlaca27 = new javax.swing.JLabel();
        lblPos28 = new javax.swing.JLabel();
        lblPlaca28 = new javax.swing.JLabel();
        lblPos29 = new javax.swing.JLabel();
        lblPlaca29 = new javax.swing.JLabel();
        lblPos30 = new javax.swing.JLabel();
        lblPlaca30 = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelResumen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrutoBicicleta = new javax.swing.JTextField();
        txtIVABicicleta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrutoMoto = new javax.swing.JTextField();
        txtIVAMoto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBrutoCarroPequeno = new javax.swing.JTextField();
        txtIVACarroPequeno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBrutoCarroGrande = new javax.swing.JTextField();
        txtIVACarroGrande = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBrutoTotal = new javax.swing.JTextField();
        txtIVATotal = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        lblIngreso = new javax.swing.JLabel();
        txtHHIngreso = new javax.swing.JTextField();
        txtMMIngreso = new javax.swing.JTextField();
        txtSSIngreso = new javax.swing.JTextField();
        lblSalida = new javax.swing.JLabel();
        txtHHSalida = new javax.swing.JTextField();
        txtMMSalida = new javax.swing.JTextField();
        txtSSSalida = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        optCarroGrande = new javax.swing.JRadioButton();
        optCarroPequeno = new javax.swing.JRadioButton();
        optMoto = new javax.swing.JRadioButton();
        optBicicleta = new javax.swing.JRadioButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdRegistrarIngreso = new javax.swing.JButton();
        cmdRegistrarSalida = new javax.swing.JButton();
        cmdConsultarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking Machine");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        setResizable(true);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking-photo.jpg"))); // NOI18N
        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblImagen, java.awt.BorderLayout.EAST);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(1, 3));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motilon-brand.png"))); // NOI18N
        lblTitulo.setToolTipText("");
        panelMenu.add(lblTitulo);

        getContentPane().add(panelMenu, java.awt.BorderLayout.NORTH);

        tabsDatos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        panelCuadricula.setBackground(new java.awt.Color(255, 255, 255));
        panelCuadricula.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        panelCuadricula.setLayout(new java.awt.GridLayout(10, 6));

        lblPos1.setBackground(new java.awt.Color(255, 255, 255));
        lblPos1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos1.setText("1");
        lblPos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos1.setOpaque(true);
        panelCuadricula.add(lblPos1);

        lblPlaca1.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca1.setOpaque(true);
        panelCuadricula.add(lblPlaca1);

        lblPos2.setBackground(new java.awt.Color(255, 255, 255));
        lblPos2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos2.setText("2");
        lblPos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos2.setOpaque(true);
        panelCuadricula.add(lblPos2);

        lblPlaca2.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca2.setOpaque(true);
        panelCuadricula.add(lblPlaca2);

        lblPos3.setBackground(new java.awt.Color(255, 255, 255));
        lblPos3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos3.setText("3");
        lblPos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos3.setOpaque(true);
        panelCuadricula.add(lblPos3);

        lblPlaca3.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca3.setOpaque(true);
        panelCuadricula.add(lblPlaca3);

        lblPos4.setBackground(new java.awt.Color(255, 255, 255));
        lblPos4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos4.setText("4");
        lblPos4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos4.setOpaque(true);
        panelCuadricula.add(lblPos4);

        lblPlaca4.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca4.setOpaque(true);
        panelCuadricula.add(lblPlaca4);

        lblPos5.setBackground(new java.awt.Color(255, 255, 255));
        lblPos5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos5.setText("5");
        lblPos5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos5.setOpaque(true);
        panelCuadricula.add(lblPos5);

        lblPlaca5.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca5.setOpaque(true);
        panelCuadricula.add(lblPlaca5);

        lblPos6.setBackground(new java.awt.Color(255, 255, 255));
        lblPos6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos6.setText("6");
        lblPos6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos6.setOpaque(true);
        panelCuadricula.add(lblPos6);

        lblPlaca6.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca6.setOpaque(true);
        panelCuadricula.add(lblPlaca6);

        lblPos7.setBackground(new java.awt.Color(255, 255, 255));
        lblPos7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos7.setText("7");
        lblPos7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos7.setOpaque(true);
        panelCuadricula.add(lblPos7);

        lblPlaca7.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca7.setOpaque(true);
        panelCuadricula.add(lblPlaca7);

        lblPos8.setBackground(new java.awt.Color(255, 255, 255));
        lblPos8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos8.setText("8");
        lblPos8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos8.setOpaque(true);
        panelCuadricula.add(lblPos8);

        lblPlaca8.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca8.setOpaque(true);
        panelCuadricula.add(lblPlaca8);

        lblPos9.setBackground(new java.awt.Color(255, 255, 255));
        lblPos9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos9.setText("9");
        lblPos9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos9.setOpaque(true);
        panelCuadricula.add(lblPos9);

        lblPlaca9.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca9.setOpaque(true);
        panelCuadricula.add(lblPlaca9);

        lblPos10.setBackground(new java.awt.Color(255, 255, 255));
        lblPos10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos10.setText("10");
        lblPos10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos10.setOpaque(true);
        panelCuadricula.add(lblPos10);

        lblPlaca10.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca10.setOpaque(true);
        panelCuadricula.add(lblPlaca10);

        lblPos11.setBackground(new java.awt.Color(255, 255, 255));
        lblPos11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos11.setText("11");
        lblPos11.setToolTipText("");
        lblPos11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos11.setOpaque(true);
        panelCuadricula.add(lblPos11);

        lblPlaca11.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca11.setOpaque(true);
        panelCuadricula.add(lblPlaca11);

        lblPos12.setBackground(new java.awt.Color(255, 255, 255));
        lblPos12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos12.setText("12");
        lblPos12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos12.setOpaque(true);
        panelCuadricula.add(lblPos12);

        lblPlaca12.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca12.setOpaque(true);
        panelCuadricula.add(lblPlaca12);

        lblPos13.setBackground(new java.awt.Color(255, 255, 255));
        lblPos13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos13.setText("13");
        lblPos13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos13.setOpaque(true);
        panelCuadricula.add(lblPos13);

        lblPlaca13.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca13.setOpaque(true);
        panelCuadricula.add(lblPlaca13);

        lblPos14.setBackground(new java.awt.Color(255, 255, 255));
        lblPos14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos14.setText("14");
        lblPos14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos14.setOpaque(true);
        panelCuadricula.add(lblPos14);

        lblPlaca14.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca14.setOpaque(true);
        panelCuadricula.add(lblPlaca14);

        lblPos15.setBackground(new java.awt.Color(255, 255, 255));
        lblPos15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos15.setText("15");
        lblPos15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos15.setOpaque(true);
        panelCuadricula.add(lblPos15);

        lblPlaca15.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca15.setOpaque(true);
        panelCuadricula.add(lblPlaca15);

        lblPos16.setBackground(new java.awt.Color(255, 255, 255));
        lblPos16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos16.setText("16");
        lblPos16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos16.setOpaque(true);
        panelCuadricula.add(lblPos16);

        lblPlaca16.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca16.setOpaque(true);
        panelCuadricula.add(lblPlaca16);

        lblPos17.setBackground(new java.awt.Color(255, 255, 255));
        lblPos17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos17.setText("17");
        lblPos17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos17.setOpaque(true);
        panelCuadricula.add(lblPos17);

        lblPlaca17.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca17.setOpaque(true);
        panelCuadricula.add(lblPlaca17);

        lblPos18.setBackground(new java.awt.Color(255, 255, 255));
        lblPos18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos18.setText("18");
        lblPos18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos18.setOpaque(true);
        panelCuadricula.add(lblPos18);

        lblPlaca18.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca18.setOpaque(true);
        panelCuadricula.add(lblPlaca18);

        lblPos19.setBackground(new java.awt.Color(255, 255, 255));
        lblPos19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos19.setText("19");
        lblPos19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos19.setOpaque(true);
        panelCuadricula.add(lblPos19);

        lblPlaca19.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca19.setOpaque(true);
        panelCuadricula.add(lblPlaca19);

        lblPos20.setBackground(new java.awt.Color(255, 255, 255));
        lblPos20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos20.setText("20");
        lblPos20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos20.setOpaque(true);
        panelCuadricula.add(lblPos20);

        lblPlaca20.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca20.setOpaque(true);
        panelCuadricula.add(lblPlaca20);

        lblPos21.setBackground(new java.awt.Color(255, 255, 255));
        lblPos21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos21.setText("21");
        lblPos21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos21.setOpaque(true);
        panelCuadricula.add(lblPos21);

        lblPlaca21.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca21.setOpaque(true);
        panelCuadricula.add(lblPlaca21);

        lblPos22.setBackground(new java.awt.Color(255, 255, 255));
        lblPos22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos22.setText("22");
        lblPos22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos22.setOpaque(true);
        panelCuadricula.add(lblPos22);

        lblPlaca22.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca22.setOpaque(true);
        panelCuadricula.add(lblPlaca22);

        lblPos23.setBackground(new java.awt.Color(255, 255, 255));
        lblPos23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos23.setText("23");
        lblPos23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos23.setOpaque(true);
        panelCuadricula.add(lblPos23);

        lblPlaca23.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca23.setOpaque(true);
        panelCuadricula.add(lblPlaca23);

        lblPos24.setBackground(new java.awt.Color(255, 255, 255));
        lblPos24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos24.setText("24");
        lblPos24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos24.setOpaque(true);
        panelCuadricula.add(lblPos24);

        lblPlaca24.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca24.setOpaque(true);
        panelCuadricula.add(lblPlaca24);

        lblPos25.setBackground(new java.awt.Color(255, 255, 255));
        lblPos25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos25.setText("25");
        lblPos25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos25.setOpaque(true);
        panelCuadricula.add(lblPos25);

        lblPlaca25.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca25.setOpaque(true);
        panelCuadricula.add(lblPlaca25);

        lblPos26.setBackground(new java.awt.Color(255, 255, 255));
        lblPos26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos26.setText("26");
        lblPos26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos26.setOpaque(true);
        panelCuadricula.add(lblPos26);

        lblPlaca26.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca26.setOpaque(true);
        panelCuadricula.add(lblPlaca26);

        lblPos27.setBackground(new java.awt.Color(255, 255, 255));
        lblPos27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos27.setText("27");
        lblPos27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos27.setOpaque(true);
        panelCuadricula.add(lblPos27);

        lblPlaca27.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca27.setOpaque(true);
        panelCuadricula.add(lblPlaca27);

        lblPos28.setBackground(new java.awt.Color(255, 255, 255));
        lblPos28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos28.setText("28");
        lblPos28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos28.setOpaque(true);
        panelCuadricula.add(lblPos28);

        lblPlaca28.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca28.setOpaque(true);
        panelCuadricula.add(lblPlaca28);

        lblPos29.setBackground(new java.awt.Color(255, 255, 255));
        lblPos29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos29.setText("29");
        lblPos29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos29.setOpaque(true);
        panelCuadricula.add(lblPos29);

        lblPlaca29.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca29.setOpaque(true);
        panelCuadricula.add(lblPlaca29);

        lblPos30.setBackground(new java.awt.Color(255, 255, 255));
        lblPos30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPos30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPos30.setText("30");
        lblPos30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPos30.setOpaque(true);
        panelCuadricula.add(lblPos30);

        lblPlaca30.setBackground(new java.awt.Color(255, 255, 255));
        lblPlaca30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPlaca30.setOpaque(true);
        panelCuadricula.add(lblPlaca30);

        tabsDatos.addTab("Vehículos Parqueados", panelCuadricula);

        panelHistorial.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        panelHistorial.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Placa", "Tiempo Servicio", "Valor Servicio $"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        panelHistorial.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabsDatos.addTab("Historial", panelHistorial);

        panelResumen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        panelResumen.setLayout(new java.awt.GridLayout(6, 3));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Servicio");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Valor Bruto $$$");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(jLabel13);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Impuesto IVA $$$");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(jLabel10);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Bicicletas:");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        panelResumen.add(jLabel2);

        txtBrutoBicicleta.setEditable(false);
        txtBrutoBicicleta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrutoBicicleta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBrutoBicicleta.setText("0");
        txtBrutoBicicleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtBrutoBicicleta);

        txtIVABicicleta.setEditable(false);
        txtIVABicicleta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIVABicicleta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVABicicleta.setText("0");
        txtIVABicicleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtIVABicicleta);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Motos:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        panelResumen.add(jLabel4);

        txtBrutoMoto.setEditable(false);
        txtBrutoMoto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrutoMoto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBrutoMoto.setText("0");
        txtBrutoMoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtBrutoMoto);

        txtIVAMoto.setEditable(false);
        txtIVAMoto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIVAMoto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVAMoto.setText("0");
        txtIVAMoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtIVAMoto);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Carros Pequeños:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        panelResumen.add(jLabel7);

        txtBrutoCarroPequeno.setEditable(false);
        txtBrutoCarroPequeno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrutoCarroPequeno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBrutoCarroPequeno.setText("0");
        txtBrutoCarroPequeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtBrutoCarroPequeno);

        txtIVACarroPequeno.setEditable(false);
        txtIVACarroPequeno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIVACarroPequeno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVACarroPequeno.setText("0");
        txtIVACarroPequeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtIVACarroPequeno);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Carros Grandes:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        panelResumen.add(jLabel8);

        txtBrutoCarroGrande.setEditable(false);
        txtBrutoCarroGrande.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrutoCarroGrande.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBrutoCarroGrande.setText("0");
        txtBrutoCarroGrande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtBrutoCarroGrande);

        txtIVACarroGrande.setEditable(false);
        txtIVACarroGrande.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIVACarroGrande.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVACarroGrande.setText("0");
        txtIVACarroGrande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtIVACarroGrande);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Totales:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        panelResumen.add(jLabel9);

        txtBrutoTotal.setEditable(false);
        txtBrutoTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrutoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBrutoTotal.setText("0");
        txtBrutoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtBrutoTotal);

        txtIVATotal.setEditable(false);
        txtIVATotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIVATotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVATotal.setText("0");
        txtIVATotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelResumen.add(txtIVATotal);

        tabsDatos.addTab("Resumen Financiero", panelResumen);

        getContentPane().add(tabsDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setLayout(new java.awt.GridLayout(5, 4));

        lblIngreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIngreso.setText("Hora de Ingreso (HH24:MI:SS):");
        lblIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblIngreso);

        txtHHIngreso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHHIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHHIngreso.setText("0");
        txtHHIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtHHIngreso);

        txtMMIngreso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMMIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMMIngreso.setText("0");
        txtMMIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtMMIngreso);

        txtSSIngreso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSSIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSSIngreso.setText("0");
        txtSSIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtSSIngreso);

        lblSalida.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSalida.setText("Hora de Salida (HH24:MI:SS):");
        lblSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblSalida);

        txtHHSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHHSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHHSalida.setText("0");
        txtHHSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtHHSalida);

        txtMMSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMMSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMMSalida.setText("0");
        txtMMSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtMMSalida);

        txtSSSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSSSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSSSalida.setText("0");
        txtSSSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtSSSalida);

        lblCedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCedula.setText("Cedula Propietario:");
        lblCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblCedula);

        txtCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setText("0");
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtCedula);

        lblPlaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPlaca.setText("Placa del Vehículo:");
        lblPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblPlaca);

        txtPlaca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setText("0");
        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(txtPlaca);

        cmdgTipoVehiculo.add(optCarroGrande);
        optCarroGrande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        optCarroGrande.setText("Carro Grande");
        optCarroGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBotones.add(optCarroGrande);

        cmdgTipoVehiculo.add(optCarroPequeno);
        optCarroPequeno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        optCarroPequeno.setText("Carro Pequeño");
        optCarroPequeno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBotones.add(optCarroPequeno);

        cmdgTipoVehiculo.add(optMoto);
        optMoto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        optMoto.setText("Motocicleta");
        optMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBotones.add(optMoto);

        cmdgTipoVehiculo.add(optBicicleta);
        optBicicleta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        optBicicleta.setText("Bicicleta");
        optBicicleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBotones.add(optBicicleta);

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(cmdLimpiar);

        cmdRegistrarIngreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRegistrarIngreso.setText("Registrar Ingreso");
        cmdRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarIngresoActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRegistrarIngreso);

        cmdRegistrarSalida.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRegistrarSalida.setText("Registrar Salida");
        cmdRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarSalidaActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRegistrarSalida);

        cmdConsultarVehiculo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdConsultarVehiculo.setText("Consultar Vehículo");
        cmdConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarVehiculoActionPerformed(evt);
            }
        });
        panelBotones.add(cmdConsultarVehiculo);

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarIngresoActionPerformed
        boolean rta = false;
        try {
            if(!(new Hora(Integer.parseInt(txtHHIngreso.getText()), Integer.parseInt(txtMMIngreso.getText()), Integer.parseInt(txtSSIngreso.getText()))).esHoraValida())
              throw new Exception("Hora de Ingreso no es valida");
              
            if (optCarroGrande.isSelected()) {
                rta = parqueadero.ingresarVehiculo(new CarroGrande(txtPlaca.getText(), txtCedula.getText(),
                        Integer.parseInt(txtHHIngreso.getText()),
                        Integer.parseInt(txtMMIngreso.getText()),
                        Integer.parseInt(txtSSIngreso.getText())));
            } else if (optCarroPequeno.isSelected()) {
                rta = parqueadero.ingresarVehiculo(new CarroPequeno(txtPlaca.getText(), txtCedula.getText(),
                        Integer.parseInt(txtHHIngreso.getText()),
                        Integer.parseInt(txtMMIngreso.getText()),
                        Integer.parseInt(txtSSIngreso.getText())));
            } else if (optMoto.isSelected()) {
                rta = parqueadero.ingresarVehiculo(new Moto(txtPlaca.getText(), txtCedula.getText(),
                        Integer.parseInt(txtHHIngreso.getText()),
                        Integer.parseInt(txtMMIngreso.getText()),
                        Integer.parseInt(txtSSIngreso.getText())));
            } else if (optBicicleta.isSelected()) {
                rta = parqueadero.ingresarVehiculo(new Bicicleta(txtPlaca.getText(), txtCedula.getText(),
                        Integer.parseInt(txtHHIngreso.getText()),
                        Integer.parseInt(txtMMIngreso.getText()),
                        Integer.parseInt(txtSSIngreso.getText())));
            } else {
                throw new RuntimeException("Debe seleccionar un tipo de Vehiculo");
            }
            if(rta){
             actualizarGUI();
             JOptionPane.showMessageDialog(this, "Registro exitoso", "Parking Machine Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
              throw new RuntimeException("No se pudo registrar...revise...");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar Ingreso: " + e.getMessage(), "Parking Machine Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmdRegistrarIngresoActionPerformed

    private void cmdRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarSalidaActionPerformed
        Vehiculo vehiculo = null;
        boolean rta = false;
        try {
            vehiculo = parqueadero.retirarVehiculo(txtPlaca.getText(),
                    Integer.parseInt(txtHHSalida.getText()),
                    Integer.parseInt(txtMMSalida.getText()),
                    Integer.parseInt(txtSSSalida.getText()));
            if((new Hora(Integer.parseInt(txtHHSalida.getText()), Integer.parseInt(txtMMSalida.getText()), Integer.parseInt(txtSSSalida.getText()))).esHoraValida())
              throw new Exception("Hora de Salida no es valida");
            if(vehiculo!=null){
             actualizarGUI();
             JOptionPane.showMessageDialog(this, "********** Registro exitoso **********\n\n" + "\n\nTarifa: $ " + vehiculo.getTarifa() + "\n\nTiempo Total: " + f.format(vehiculo.getTiempoServicio()) + "\n\nTotal a Pagar: $ " + f.format(vehiculo.getValorTotalServicio()), "Parking Machine Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else throw new Exception("No se pudo registrar...revise...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar Salida: " + e.getMessage(), "Parking Machine Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmdRegistrarSalidaActionPerformed

    private void cmdConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarVehiculoActionPerformed
        int posicion = parqueadero.buscarVehiculo(txtPlaca.getText());
        actualizarGUI();
        if (posicion != -1) {
            lblPosicion[posicion].setBackground(new Color(139, 214, 188));
            actualizarDatos(parqueadero.getVehiculos()[posicion]);
        } else {
            JOptionPane.showMessageDialog(this, "Vehiculo no existe", "Parking Machine Information", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmdConsultarVehiculoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtHHIngreso.setText("0");
        txtMMIngreso.setText("0");
        txtSSIngreso.setText("0");
        txtHHSalida.setText("0");
        txtMMSalida.setText("0");
        txtSSSalida.setText("0");
        txtPlaca.setText("0");
        txtCedula.setText("0");
        optCarroGrande.setSelected(false);
        optCarroPequeno.setSelected(false);
        optMoto.setSelected(false);
        optBicicleta.setSelected(false);
        actualizarGUI();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdConsultarVehiculo;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdRegistrarIngreso;
    private javax.swing.JButton cmdRegistrarSalida;
    private javax.swing.ButtonGroup cmdgTipoVehiculo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPlaca10;
    private javax.swing.JLabel lblPlaca11;
    private javax.swing.JLabel lblPlaca12;
    private javax.swing.JLabel lblPlaca13;
    private javax.swing.JLabel lblPlaca14;
    private javax.swing.JLabel lblPlaca15;
    private javax.swing.JLabel lblPlaca16;
    private javax.swing.JLabel lblPlaca17;
    private javax.swing.JLabel lblPlaca18;
    private javax.swing.JLabel lblPlaca19;
    private javax.swing.JLabel lblPlaca2;
    private javax.swing.JLabel lblPlaca20;
    private javax.swing.JLabel lblPlaca21;
    private javax.swing.JLabel lblPlaca22;
    private javax.swing.JLabel lblPlaca23;
    private javax.swing.JLabel lblPlaca24;
    private javax.swing.JLabel lblPlaca25;
    private javax.swing.JLabel lblPlaca26;
    private javax.swing.JLabel lblPlaca27;
    private javax.swing.JLabel lblPlaca28;
    private javax.swing.JLabel lblPlaca29;
    private javax.swing.JLabel lblPlaca3;
    private javax.swing.JLabel lblPlaca30;
    private javax.swing.JLabel lblPlaca4;
    private javax.swing.JLabel lblPlaca5;
    private javax.swing.JLabel lblPlaca6;
    private javax.swing.JLabel lblPlaca7;
    private javax.swing.JLabel lblPlaca8;
    private javax.swing.JLabel lblPlaca9;
    private javax.swing.JLabel lblPos1;
    private javax.swing.JLabel lblPos10;
    private javax.swing.JLabel lblPos11;
    private javax.swing.JLabel lblPos12;
    private javax.swing.JLabel lblPos13;
    private javax.swing.JLabel lblPos14;
    private javax.swing.JLabel lblPos15;
    private javax.swing.JLabel lblPos16;
    private javax.swing.JLabel lblPos17;
    private javax.swing.JLabel lblPos18;
    private javax.swing.JLabel lblPos19;
    private javax.swing.JLabel lblPos2;
    private javax.swing.JLabel lblPos20;
    private javax.swing.JLabel lblPos21;
    private javax.swing.JLabel lblPos22;
    private javax.swing.JLabel lblPos23;
    private javax.swing.JLabel lblPos24;
    private javax.swing.JLabel lblPos25;
    private javax.swing.JLabel lblPos26;
    private javax.swing.JLabel lblPos27;
    private javax.swing.JLabel lblPos28;
    private javax.swing.JLabel lblPos29;
    private javax.swing.JLabel lblPos3;
    private javax.swing.JLabel lblPos30;
    private javax.swing.JLabel lblPos4;
    private javax.swing.JLabel lblPos5;
    private javax.swing.JLabel lblPos6;
    private javax.swing.JLabel lblPos7;
    private javax.swing.JLabel lblPos8;
    private javax.swing.JLabel lblPos9;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton optBicicleta;
    private javax.swing.JRadioButton optCarroGrande;
    private javax.swing.JRadioButton optCarroPequeno;
    private javax.swing.JRadioButton optMoto;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCuadricula;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JTabbedPane tabsDatos;
    private javax.swing.JTextField txtBrutoBicicleta;
    private javax.swing.JTextField txtBrutoCarroGrande;
    private javax.swing.JTextField txtBrutoCarroPequeno;
    private javax.swing.JTextField txtBrutoMoto;
    private javax.swing.JTextField txtBrutoTotal;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtHHIngreso;
    private javax.swing.JTextField txtHHSalida;
    private javax.swing.JTextField txtIVABicicleta;
    private javax.swing.JTextField txtIVACarroGrande;
    private javax.swing.JTextField txtIVACarroPequeno;
    private javax.swing.JTextField txtIVAMoto;
    private javax.swing.JTextField txtIVATotal;
    private javax.swing.JTextField txtMMIngreso;
    private javax.swing.JTextField txtMMSalida;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSSIngreso;
    private javax.swing.JTextField txtSSSalida;
    // End of variables declaration//GEN-END:variables

    private void actualizarGUI() {
        actualizarCuadricula();
        actualizarResumen();
        actualizarHistorial();
    }

    private void actualizarCuadricula() {
        Vehiculo[] vehiculos = parqueadero.getVehiculos();
        String icono = null;
        for (int i = 0; i < lblLugarParqueo.length; i++) {
            icono = "";
            if (vehiculos[i] instanceof CarroPequeno) {
                icono = "carropequeno.png";
            }
            if (vehiculos[i] instanceof CarroGrande) {
                icono = "carrogrande.png";
            }
            if (vehiculos[i] instanceof Moto) {
                icono = "moto.png";
            }
            if (vehiculos[i] instanceof Bicicleta) {
                icono = "bicicleta.png";
            }
            if (vehiculos[i] != null) {
                lblLugarParqueo[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(icono)));
            } else {
                lblLugarParqueo[i].setIcon(null);
            }
            lblPosicion[i].setBackground(new Color(255, 255, 255));
        }
    }

    private void actualizarResumen() {
        double a = 0, b = 0, c = 0, d = 0;
        a = parqueadero.getValorBrutoServicio(1);
        b = parqueadero.getValorBrutoServicio(2);
        c = parqueadero.getValorBrutoServicio(3);
        d = parqueadero.getValorBrutoServicio(4);
        txtBrutoBicicleta.setText(f.format(a));
        txtBrutoMoto.setText(f.format(b));
        txtBrutoCarroPequeno.setText(f.format(c));
        txtBrutoCarroGrande.setText(f.format(d));
        txtBrutoTotal.setText(f.format(a + b + c + d));
        a = a * 0.19;
        b = b * 0.19;
        c = c * 0.19;
        d = d * 0.19;
        txtIVABicicleta.setText(f.format(a));
        txtIVAMoto.setText(f.format(b));
        txtIVACarroPequeno.setText(f.format(c));
        txtIVACarroGrande.setText(f.format(d));
        txtIVATotal.setText(f.format(a + b + c + d));
    }

    private void actualizarHistorial() {
        ArrayList<Vehiculo> historial = parqueadero.getHistorialVehiculos();
        String[][] tabla = new String[historial.size()][4];

        for (int i = 0; i < tabla.length; i++) {
            tabla[i][0] = String.valueOf(i+1);
            tabla[i][1] = historial.get(i).getPlaca();
            tabla[i][2] = f.format(historial.get(i).getTiempoServicio());
            tabla[i][3] = f.format(historial.get(i).getValorTotalServicio());
        }

        jTable1.setModel(new DefaultTableModel(
                tabla,
                new String[]{
                    "No", "Placa", "Tiempo Servicio", "Valor Servicio $"
                }
        ) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

    }

    private void actualizarDatos(Vehiculo v) {
        Hora h = v.getHoraIngreso();

        txtHHIngreso.setText(String.valueOf(h.getHoras()));
        txtMMIngreso.setText(String.valueOf(h.getMinutos()));
        txtSSIngreso.setText(String.valueOf(h.getSegundos()));
        txtPlaca.setText(v.getPlaca());
        txtCedula.setText(v.getCedulaPropietario());

        optCarroGrande.setSelected(false);
        optCarroPequeno.setSelected(false);
        optMoto.setSelected(false);
        optBicicleta.setSelected(false);
        if (v instanceof CarroPequeno) {
            optCarroPequeno.setSelected(true);
        }
        if (v instanceof CarroGrande) {
            optCarroGrande.setSelected(true);
        }
        if (v instanceof Moto) {
            optMoto.setSelected(true);
        }
        if (v instanceof Bicicleta) {
            optBicicleta.setSelected(true);
        }
    }

    /**
     * Listener para el click de cada etiqueta
     */
    private class ParkingLabelListener implements MouseListener {

        private int posicion;

        public ParkingLabelListener(int posicion) {
            this.posicion = posicion;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            Vehiculo v = parqueadero.getVehiculos()[posicion];
            actualizarGUI();
            if (v != null) {
                if (lblPosicion[posicion].getBackground().equals(Color.WHITE)) {
                    lblPosicion[posicion].setBackground(new Color(139, 214, 188));
                    actualizarDatos(v);
                } else {
                    lblPosicion[posicion].setBackground(Color.WHITE);
                }
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {;
        }

        @Override
        public void mouseReleased(MouseEvent e) {;
        }

        @Override
        public void mouseEntered(MouseEvent e) {;
        }

        @Override
        public void mouseExited(MouseEvent e) {;
        }

    }

}
