apiVersion: v1
kind: Service
metadata:
  name: client-service-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  ports:
    - name: "80"
      port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: client
  type: LoadBalancer
