version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vpladmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: vpl
    networks:
      - vpl
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data
  mysql:
    image: "mysql:5.7.21"
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - vpl
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  moodle:
    image: alphonse92/moodle
    environment:
      DB_CONNECTOR: mysqli
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: moodle
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PREFIX: mdl_
      MOODLE_URL: http://localhost:8080
    networks:
      - vpl
    ports:
      - "8080:80"
    volumes:
      - ./data/moodle_data:/var/moodle_data
      - ./data/moodle:/var/www/html
  jail:
    image: alphonse92/vpl-jail-execution-vpl-jlib-runner
    environment:
      ENV: production
      API_URL: http://10.0.75.6:1337/api/v1/project/test/case/summary/
      API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGNhZTg4ZjNiZDhlMTAwMjVjNzdmZmQiLCJpZCI6LTE1NzM1Nzg4OTUyMTgsInVzZXJuYW1lIjoiYXNkYXNkIiwidHlwZSI6ImFwaV9jbGllbnQiLCJpYXQiOjE1NzM1Nzg4OTV9.8OLpDntoX-ZDUGIrKjiQiU8g7TKEv86pss4kF0DePEU
      JAIL_PORT: 9999
      JAIL_SECURE_PORT: 4433
      API_IP: 10.0.75.6
      API_HOSTNAME: 'api'
    networks:
      - vpl
    ports:
      - "9999:9999"
      - "4433:4433"
    privileged: true
    cap_add:
      - ALL
  client:
    image: alphonse92/vpl_client
    environment:
        NODE_ENV: production
        REACT_APP_ENV: production
        REACT_APP_PUBLIC_URL: /
        REACT_APP_API_BASEURL: http://localhost:1337/api/v1
        REACT_APP_CLIENT_ID: 126760867544-k1es3tqiho46b0g831cmsvgokvl0npqu.apps.googleusercontent.com
    networks:
      - vpl
    ports:
      - "3000:80"
  api:
    image: alphonse92/vpl_api
    environment:
      NODE_PATH: .
      HOST: localhost
      PORT: 1337
      NODE_ENV: production
      SYSTEM_CORES: 1
      MONGO: mongodb://vpladmin:secret@mongo:27017/vpl-dev?authSource=admin
      MYSQL: mysql://root:root@mysql:3306/moodle?connectionAttributes=program_name:vplplusplus_api
      MOODLE_HOST: localhost
      MOODLE_PORT: 8080
      MOODLE_DB_PREFIX: mdl_
      MOODLE_AUTH_TYPE: saltedcrypt
      GOOGLE_CLIENT_ID: 126760867544-k1es3tqiho46b0g831cmsvgokvl0npqu.apps.googleusercontent.com
      INIT_USER_TYPE: reset
      TOKEN_SECRET: secret
      TOKEN_EXP_MINUTES: NEVER
      CACHE_FOLDER: /tmp/vplplusplus
      SHOW_CONFIG_AT_STARTUP: "true"
    networks:
      - vpl
    ports:
      - "1337:1337"
    command: npm run startdev
    volumes:
      - ./vplplusplus_api:/usr/src/
networks:
  vpl:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.75.0/24