version: "3.3"
services:
  mongo:
    container_name: vplmongo
    image: "mongo:latest"
    networks:
      - vpl
    volumes:
      - ./data/mongo:/data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vpladmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: vpl
  mysql:
    container_name: vplmysql
    image: "mysql:5.7.21"
    networks:
      - vpl
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  moodle:
    container_name: vplmoodle
    build:
      context: docker-moodle
      args:
        MOODLE_CURRENT_BRANCH: MOODLE_34_STABLE
    depends_on:
      - mysql
    networks:
      - vpl
    ports:
      - "8080:80"
    environment:
      DB_CONNECTOR: mysqli
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: moodle
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PREFIX: mdl_
      MOODLE_URL: http://localhost:8080
    volumes:
      - ./data/moodle_data:/var/moodle_data
      - ./data/moodle:/var/www/html
  jail:
    container_name: vpljail
    build:
      context: vplplusplus_jail
      args:
        VERSION: 2.5.2
    environment:
      JAIL_PORT: 8888
      JAIL_SECURE_PORT: 4433
    networks:
      - vpl
    ports:
      - "8888:8888"
    privileged: true
    cap_add:
      - ALL
  jailrunner:
    container_name: vpljailrunner
    build:
      context: vplplusplus_jail_jlib
      args: 
        JLIB_URL: https://raw.githubusercontent.com/alphonse92/vplplusplus_jlib/master/store/VPLPlusPlus-jlib.jar
    environment:
      ENV: production
      API_URL: http://api:1337/api/v1/project/test/case/summary/
      API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM3M2Q4NmUxOTY2NGFkY2U2ZmI1ZTgiLCJpZCI6LTE1NzMzMzg1MDIzNTEsInVzZXJuYW1lIjoiYXBwIiwidHlwZSI6ImFwaV9jbGllbnQiLCJpYXQiOjE1NzMzMzg1MDJ9.Liim08kZkPPlT-v5yKW9-ywvWpCSmyBMns7i8vFbIIg
      JAIL_PORT: 8888
      JAIL_SECURE_PORT: 4433
    networks:
      - vpl
    ports:
      - "8888:8888"
    privileged: true
    cap_add:
      - ALL
  client:
    container_name: client
    networks:
      - vpl
    build:
      context: ./vplplusplus_client
      args:
        PUBLIC_URL: "/"
        API_BASEURL: "http://api:1337/api/v1"
        CLIENT_ID: "126760867544-k1es3tqiho46b0g831cmsvgokvl0npqu.apps.googleusercontent.com"
    ports:
      - "3000:80"
  api:
    container_name: api
    build: vplplusplus_api
    command: npm run startdev
    volumes:
      - ./vplplusplus_api:/usr/src/app
    networks:
      - vpl
    ports:
      - "1337:1337"
    depends_on:
      - mongo
      - mysql
    environment:
      NODE_PATH: .
      HOST: localhost
      PORT: 1337
      NODE_ENV: development
      SYSTEM_CORES: 1
      MONGO: mongodb://vpladmin:secret@mongo:27017/vpl-dev?authSource=admin
      MYSQL: mysql://root:root@mysql:3306/moodle?connectionAttributes=program_name:vplplusplus_api
      MOODLE_HOST: localhost
      MOODLE_PORT: 8080
      MOODLE_DB_PREFIX: mdl_
      MOODLE_AUTH_TYPE: saltedcrypt
      GOOGLE_CLIENT_ID: 126760867544-k1es3tqiho46b0g831cmsvgokvl0npqu.apps.googleusercontent.com
      INIT_USER_TYPE: reset
      TOKEN_SECRET: secret
      TOKEN_EXP_MINUTES: NEVER
      CACHE_FOLDER: /tmp/vplplusplus
networks:
  vpl:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.75.0/24
