
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
public class LunchMachineComprarView extends javax.swing.JFrame {

    protected LunchMachineView padre;

    /**
     * Creates new form CoffeeMachineView
     */
    public LunchMachineComprarView(LunchMachineView padre) {
        this.padre = padre;
        initComponents();
        center();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblIngrediente = new javax.swing.JLabel();
        comboIngrediente = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadCompra = new javax.swing.JTextField();
        lblPrecioCompra = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        cmdRegistrarCompraIgrediente = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lunch Vending Machine - Comprar Ingredientes");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lunch-machine.png"))); // NOI18N
        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblImagen, java.awt.BorderLayout.EAST);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(1, 3));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motilon-brand.png"))); // NOI18N
        lblTitulo.setToolTipText("");
        panelMenu.add(lblTitulo);

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new java.awt.GridLayout(3, 2));

        lblIngrediente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIngrediente.setText("Ingrediente:");
        lblIngrediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblIngrediente);

        comboIngrediente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panelDatos.add(comboIngrediente);

        lblCantidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidad.setText("Cantidad a Comprar (gramos):");
        lblCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblCantidad);

        txtCantidadCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCantidadCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadCompra.setText("0");
        txtCantidadCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCantidadCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtCantidadCompra);

        lblPrecioCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompra.setText("Precio de Compra $$$ ($/gramo):");
        lblPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompra);

        txtPrecioCompra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompra.setText("0");
        txtPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompra);

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setLayout(new java.awt.GridLayout(1, 3));

        cmdRegistrarCompraIgrediente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRegistrarCompraIgrediente.setText("Registrar Compra");
        cmdRegistrarCompraIgrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarCompraIgredienteActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRegistrarCompraIgrediente);

        cmdSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdSalir.setText("Regresar...");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        panelBotones.add(cmdSalir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
        padre.actualizarGUI();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdRegistrarCompraIgredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarCompraIgredienteActionPerformed
        padre.requerimiento4(comboIngrediente.getSelectedItem().toString(), Integer.parseInt(txtCantidadCompra.getText()), Integer.parseInt(txtPrecioCompra.getText()),comboIngrediente.getSelectedIndex()/5 + 1);
    }//GEN-LAST:event_cmdRegistrarCompraIgredienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdRegistrarCompraIgrediente;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JComboBox<String> comboIngrediente;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtCantidadCompra;
    private javax.swing.JTextField txtPrecioCompra;
    // End of variables declaration//GEN-END:variables

    private void center() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    /**
     * @return the comboIngrediente
     */
    public javax.swing.JComboBox<String> getComboIngredientes() {
        return comboIngrediente;
    }
}
