
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author (Milton Jes�s Vera Contreras - miltonjeussvc@ufps.edu.co) 
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 *
 */
public class CoffeeMachineView extends javax.swing.JFrame {

    protected MaquinaCafetera maquina;

    /**
     * Creates new form CoffeeMachineView
     */
    public CoffeeMachineView() {
        //maquina = new MaquinaCafetera(1000, 1000, 125);
        maquina = new MaquinaCafetera();
        initComponents();
        cmdRegistrarFactura.setEnabled(false);
        cmdPrepararCafe.setEnabled(true);
        actualizarGUI();
        comboTipoCafe.setSelectedIndex(0);
        comboAzucar.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblCafe = new javax.swing.JLabel();
        txtCafe = new javax.swing.JTextField();
        lblAzucar = new javax.swing.JLabel();
        txtAzucar = new javax.swing.JTextField();
        lblVasos = new javax.swing.JLabel();
        txtVasos = new javax.swing.JTextField();
        lblPrecioBaseCafe = new javax.swing.JLabel();
        txtPrecioBaseCafe = new javax.swing.JTextField();
        lblIngresos = new javax.swing.JLabel();
        txtIngresos = new javax.swing.JTextField();
        lblEgresos = new javax.swing.JLabel();
        txtEgresos = new javax.swing.JTextField();
        lblGananciasBrutas = new javax.swing.JLabel();
        txtGananciasBrutas = new javax.swing.JTextField();
        lblImpuestos = new javax.swing.JLabel();
        txtImpuestos = new javax.swing.JTextField();
        lblGananciasNetas = new javax.swing.JLabel();
        txtGananciasNetas = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        comboTipoCafe = new javax.swing.JComboBox<>();
        comboAzucar = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cmdPrepararCafe = new javax.swing.JButton();
        cmdFijarPrecioBaseCafe = new javax.swing.JButton();
        cmdRecargarCafe = new javax.swing.JButton();
        cmdRecargarAzucar = new javax.swing.JButton();
        cmdRecargarVasos = new javax.swing.JButton();
        cmdRegistrarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffe Vending Machine");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        setResizable(false);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_coffee-machine.png"))); // NOI18N
        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblImagen, java.awt.BorderLayout.EAST);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(1, 3));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motilon-brand.png"))); // NOI18N
        lblTitulo.setToolTipText("");
        panelMenu.add(lblTitulo);

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new java.awt.GridLayout(9, 2));

        lblCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCafe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCafe.setText("Cantidad de Caf� (gramos):");
        lblCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblCafe);

        txtCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCafe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCafe.setText("0");
        txtCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCafe.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCafe.setEnabled(false);
        panelDatos.add(txtCafe);

        lblAzucar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAzucar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAzucar.setText("Cantidad de Az�car (gramos):");
        lblAzucar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblAzucar);

        txtAzucar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAzucar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAzucar.setText("0");
        txtAzucar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAzucar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAzucar.setEnabled(false);
        panelDatos.add(txtAzucar);

        lblVasos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVasos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVasos.setText("Cantidad de Vasos (unidad):");
        lblVasos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblVasos);

        txtVasos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtVasos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVasos.setText("0");
        txtVasos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtVasos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtVasos.setEnabled(false);
        panelDatos.add(txtVasos);

        lblPrecioBaseCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioBaseCafe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioBaseCafe.setText("Precio Base Caf� $$$:");
        lblPrecioBaseCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioBaseCafe);

        txtPrecioBaseCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioBaseCafe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioBaseCafe.setText("0");
        txtPrecioBaseCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioBaseCafe.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecioBaseCafe.setEnabled(false);
        panelDatos.add(txtPrecioBaseCafe);

        lblIngresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIngresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIngresos.setText("Total de Ingresos $$$:");
        lblIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblIngresos);

        txtIngresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtIngresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIngresos.setText("0");
        txtIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIngresos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIngresos.setEnabled(false);
        panelDatos.add(txtIngresos);

        lblEgresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEgresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEgresos.setText("Total de Egresos $$$:");
        lblEgresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblEgresos);

        txtEgresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtEgresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEgresos.setText("0");
        txtEgresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEgresos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEgresos.setEnabled(false);
        panelDatos.add(txtEgresos);

        lblGananciasBrutas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGananciasBrutas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGananciasBrutas.setText("Ganancias antes de IVA $$$:");
        lblGananciasBrutas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblGananciasBrutas);

        txtGananciasBrutas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGananciasBrutas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGananciasBrutas.setText("0");
        txtGananciasBrutas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGananciasBrutas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGananciasBrutas.setEnabled(false);
        panelDatos.add(txtGananciasBrutas);

        lblImpuestos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblImpuestos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImpuestos.setText("IVA $$$:");
        lblImpuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblImpuestos);

        txtImpuestos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtImpuestos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtImpuestos.setText("0");
        txtImpuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtImpuestos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtImpuestos.setEnabled(false);
        panelDatos.add(txtImpuestos);

        lblGananciasNetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGananciasNetas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGananciasNetas.setText("Ganancias Netas $$$:");
        lblGananciasNetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblGananciasNetas);

        txtGananciasNetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGananciasNetas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGananciasNetas.setText("0");
        txtGananciasNetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGananciasNetas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGananciasNetas.setEnabled(false);
        panelDatos.add(txtGananciasNetas);

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setLayout(new java.awt.GridLayout(2, 5));

        comboTipoCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboTipoCafe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Tinto Sencillo", "2- Tinto Normal", "3- Tinto Doble" }));
        comboTipoCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCafeActionPerformed(evt);
            }
        });
        panelBotones.add(comboTipoCafe);

        comboAzucar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboAzucar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Sin Az�car", "2- Bajo en Az�car", "3- Normal" }));
        comboAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAzucarActionPerformed(evt);
            }
        });
        panelBotones.add(comboAzucar);

        lblPrecio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio $$$:");
        panelBotones.add(lblPrecio);

        txtPrecio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.setText("0");
        txtPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecio.setEnabled(false);
        panelBotones.add(txtPrecio);

        cmdPrepararCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdPrepararCafe.setText("Preparar Caf�");
        cmdPrepararCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrepararCafeActionPerformed(evt);
            }
        });
        panelBotones.add(cmdPrepararCafe);

        cmdFijarPrecioBaseCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdFijarPrecioBaseCafe.setText("Fijar Precio Base Caf�");
        cmdFijarPrecioBaseCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFijarPrecioBaseCafeActionPerformed(evt);
            }
        });
        panelBotones.add(cmdFijarPrecioBaseCafe);

        cmdRecargarCafe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRecargarCafe.setText("Recargar Caf�");
        cmdRecargarCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecargarCafeActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRecargarCafe);

        cmdRecargarAzucar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRecargarAzucar.setText("Recargar Az�car");
        cmdRecargarAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecargarAzucarActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRecargarAzucar);

        cmdRecargarVasos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRecargarVasos.setText("Recargar Vasos");
        cmdRecargarVasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecargarVasosActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRecargarVasos);

        cmdRegistrarFactura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRegistrarFactura.setText("Registrar Factura");
        cmdRegistrarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarFacturaActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRegistrarFactura);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCafeActionPerformed
        int cafe = comboTipoCafe.getSelectedIndex() + 1;
        int azucar = comboAzucar.getSelectedIndex() + 1;
        int precio = maquina.calcularPrecio(cafe, azucar);
        txtPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_comboTipoCafeActionPerformed

    private void comboAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAzucarActionPerformed
        int azucar = comboAzucar.getSelectedIndex() + 1;
        int cafe = comboTipoCafe.getSelectedIndex() + 1;
        int precio = maquina.calcularPrecio(cafe, azucar);
        txtPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_comboAzucarActionPerformed

    private void cmdRecargarCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecargarCafeActionPerformed
        DialogoCafetera dialogo = new DialogoCafetera(this, "Caf�");
        int cantidad = 0;
        int costo = 0;;
        if (dialogo.ok()) {
            cantidad = dialogo.getCantidad();
            costo = dialogo.getCosto();
        }
        if (maquina.recargarCafe(cantidad, costo)) {
            JOptionPane.showMessageDialog(null, "La informaci�n se registr� correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "No se posible comprar caf�, no hay capital suficiente...");
        }
        actualizarGUI();
    }//GEN-LAST:event_cmdRecargarCafeActionPerformed

    private void cmdRecargarAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecargarAzucarActionPerformed
        DialogoCafetera dialogo = new DialogoCafetera(this, "Azucar");
        int cantidad = 0;
        int costo = 0;;
        if (dialogo.ok()) {
            cantidad = dialogo.getCantidad();
            costo = dialogo.getCosto();
        }
        if (maquina.recargarAzucar(cantidad, costo)) {
            JOptionPane.showMessageDialog(null, "La informaci�n se registr� correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "No es posible comprar az�car, no hay capital suficiente...");
        }
        actualizarGUI();
    }//GEN-LAST:event_cmdRecargarAzucarActionPerformed

    private void cmdRecargarVasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecargarVasosActionPerformed
        DialogoCafetera dialogo = new DialogoCafetera(this, "Vasos");
        int cantidad = 0;
        int costo = 0;;
        if (dialogo.ok()) {
            cantidad = dialogo.getCantidad();
            costo = dialogo.getCosto();
        }
        if (maquina.recargarVasos(cantidad, costo)) {
            JOptionPane.showMessageDialog(null, "La informaci�n se registr� correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "No es posible comprar vasos, no hay capital suficiente...");
        }
        actualizarGUI();
    }//GEN-LAST:event_cmdRecargarVasosActionPerformed

    private void cmdPrepararCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrepararCafeActionPerformed
        int cafe = comboTipoCafe.getSelectedIndex() + 1;
        int azucar = comboAzucar.getSelectedIndex() + 1;
        if (maquina.prepararCafe(cafe, azucar)) {
            cmdPrepararCafe.setEnabled(false);
            cmdRegistrarFactura.setEnabled(true);
            comboTipoCafe.setEnabled(false);
            comboAzucar.setEnabled(false);
            actualizarGUI();
            JOptionPane.showMessageDialog(null, "Se prepar� el Caf� correctamente. por favor Registre la Factura");
        } else {
            JOptionPane.showMessageDialog(null, "No es posible preparar caf�, no hay insumos suficientes...");
        }
    }//GEN-LAST:event_cmdPrepararCafeActionPerformed

    private void cmdFijarPrecioBaseCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFijarPrecioBaseCafeActionPerformed
        int precioKiloCafe = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Precio Base del Caf�\n http://www.federaciondecafeteros.org/static/files/precio_cafe.pdf"));
        maquina.setPrecioBaseCafe(precioKiloCafe);        
        actualizarGUI();
        comboTipoCafe.setSelectedIndex(0);
        comboAzucar.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null, "La informaci�n se registr� correctamente");
    }//GEN-LAST:event_cmdFijarPrecioBaseCafeActionPerformed

    private void cmdRegistrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarFacturaActionPerformed
        int precio = Integer.parseInt(txtPrecio.getText());
        maquina.registrarFactura(precio);
        cmdRegistrarFactura.setEnabled(false);
        cmdPrepararCafe.setEnabled(true);
        comboTipoCafe.setEnabled(true);
        comboAzucar.setEnabled(true);
        actualizarGUI();
        JOptionPane.showMessageDialog(null, "La informaci�n se registr� correctamente");
    }//GEN-LAST:event_cmdRegistrarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeMachineView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdFijarPrecioBaseCafe;
    private javax.swing.JButton cmdPrepararCafe;
    private javax.swing.JButton cmdRecargarAzucar;
    private javax.swing.JButton cmdRecargarCafe;
    private javax.swing.JButton cmdRecargarVasos;
    private javax.swing.JButton cmdRegistrarFactura;
    private javax.swing.JComboBox<String> comboAzucar;
    private javax.swing.JComboBox<String> comboTipoCafe;
    private javax.swing.JLabel lblAzucar;
    private javax.swing.JLabel lblCafe;
    private javax.swing.JLabel lblEgresos;
    private javax.swing.JLabel lblGananciasBrutas;
    private javax.swing.JLabel lblGananciasNetas;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioBaseCafe;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVasos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtAzucar;
    private javax.swing.JTextField txtCafe;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtGananciasBrutas;
    private javax.swing.JTextField txtGananciasNetas;
    private javax.swing.JTextField txtImpuestos;
    private javax.swing.JTextField txtIngresos;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioBaseCafe;
    private javax.swing.JTextField txtVasos;
    // End of variables declaration//GEN-END:variables

    private void actualizarGUI() {
        txtCafe.setText(String.valueOf(maquina.getCafe()));
        txtAzucar.setText(String.valueOf(maquina.getAzucar()));
        txtVasos.setText(String.valueOf(maquina.getVasos()));
        txtPrecioBaseCafe.setText(String.valueOf(maquina.getPrecioBaseCafe()));
        txtIngresos.setText(String.valueOf(maquina.getIngresos()));
        txtEgresos.setText(String.valueOf(maquina.getEgresos()));
        txtGananciasBrutas.setText(String.valueOf(maquina.getGananciasBrutas()));
        txtImpuestos.setText(String.valueOf(maquina.getImpuestos()));
        txtGananciasNetas.setText(String.valueOf(maquina.getGananciasNetas()));
        if (maquina.getGananciasBrutas() < 0) {
            txtGananciasBrutas.setForeground(new Color(255, 0, 0));
        } else {
            txtGananciasBrutas.setForeground(new Color(0, 0, 0));
        }
        if (maquina.getGananciasNetas() < 0) {
            txtGananciasNetas.setDisabledTextColor(new Color(255, 0, 0));
        } else {
            txtGananciasNetas.setDisabledTextColor(new Color(0, 0, 0));
        }
    }

    /**
     * ********************************************************************************
     */
    /* Se declara como una clase interna el Cuadro de Dialogo para recargar los insumos de la cefetera*/
    public class DialogoCafetera extends JDialog {

        private JLabel lblCantidad;
        private JLabel lblCosto;
        private JTextField txtCantidad;
        private JTextField txtCosto;
        private JButton cmdAceptar;
        private JButton cmdCancelar;
        private boolean ok;

        public DialogoCafetera(JFrame owner, String prefijoInsumo) {
            super(owner, true);
            lblCantidad = new JLabel();
            lblCosto = new JLabel();
            txtCantidad = new JTextField();
            txtCosto = new JTextField();
            cmdAceptar = new JButton();
            cmdCancelar = new JButton();

            setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            setLayout(new GridLayout(3, 2));

            lblCantidad.setFont(new Font("Time New Roman", 1, 20));
            lblCantidad.setText("Cantidad de " + prefijoInsumo);
            lblCantidad.setHorizontalTextPosition(SwingConstants.CENTER);
            add(lblCantidad);

            txtCantidad.setBackground(new Color(255, 255, 255));
            txtCantidad.setFont(new Font("Time New Roman", 0, 20));
            txtCantidad.setHorizontalAlignment(JTextField.CENTER);
            txtCantidad.setText("0");
            add(txtCantidad);

            lblCosto.setFont(new Font("Time New Roman", 1, 20));
            lblCosto.setText("Precio $$$ de " + prefijoInsumo);
            lblCosto.setHorizontalTextPosition(SwingConstants.CENTER);
            add(lblCosto);

            txtCosto.setBackground(new Color(255, 255, 255));
            txtCosto.setFont(new Font("Time New Roman", 0, 20));
            txtCosto.setHorizontalAlignment(JTextField.CENTER);
            txtCosto.setText("0");
            add(txtCosto);

            cmdAceptar.setFont(new Font("Time New Roman", 1, 20));
            cmdAceptar.setText("Aceptar");
            add(cmdAceptar);
            cmdCancelar.setFont(new Font("Time New Roman", 1, 20));
            cmdCancelar.setText("Cancelar");
            add(cmdCancelar);

            //clase anónima para eventos de boton
            cmdAceptar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    cmdAceptarActionPerformed(evt);
                }
            });

            //clase anónima para eventos de boton
            cmdCancelar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    cmdCancelarActionPerformed(evt);
                }
            });

            pack();
            setResizable(false);
            setLocation(owner.getX() + (owner.getWidth() / 2 - this.getWidth() / 2), owner.getY() + (owner.getHeight() / 2 - this.getHeight() / 2));
            setTitle("Ingrese la Cantidad y Precio de " + prefijoInsumo);
            setVisible(true);
        }//fin constructor clase interna GUIApuesta

        /**
         * Evento click cmdAceptar
         */
        private void cmdAceptarActionPerformed(ActionEvent evt) {
            this.ok = true;
            this.setVisible(false);
        }//fin cmdAceptarActionPerformed

        /**
         * Evento click cmdCancelar
         */
        private void cmdCancelarActionPerformed(ActionEvent evt) {
            this.ok = false;
            this.setVisible(false);
        }//fin cmdCancelarActionPerformed

        public int getCantidad() {
            return Integer.parseInt(txtCantidad.getText());
        }

        public int getCosto() {
            return Integer.parseInt(txtCosto.getText());
        }

        public boolean ok() {
            return this.ok;
        }
    }//fin class DialogoTarifa
}
