ENVIRONMENT: development
NODE_PATH: .
HOST: localhost
PORT: 1337
NODE_ENV: production
SYSTEM_CORES: 1
MONGO: mongodb://vpladmin:secret@mongo:27017/vpl-dev?authSource=admin
MYSQL: mysql://root:root@mysql:3306/moodle?connectionAttributes=program_name:vplplusplus_api
MOODLE_HOST: localhost
MOODLE_PORT: 8080
MOODLE_DB_PREFIX: mdl_
MOODLE_AUTH_TYPE: saltedcrypt
GOOGLE_CLIENT_ID: 126760867544-k1es3tqiho46b0g831cmsvgokvl0npqu.apps.googleusercontent.com
INIT_USER_TYPE: reset
TOKEN_SECRET: secret
TOKEN_EXP_MINUTES: NEVER
CACHE_FOLDER: /tmp/vplplusplus
SHOW_CONFIG_AT_STARTUP: "true"