kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
data:
  MYSQL_DATABASE: {{MYSQL_DATABASE}}
  MYSQL_USER: {{MYSQL_USER}}
  MYSQL_PASSWORD: {{MYSQL_PASSWORD}}
  MYSQL_ROOT_PASSWORD: {{MYSQL_ROOT_PASSWORD}}