apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-{{ENVIRONMENT}}
  namespace: {{ENVIRONMENT}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-{{ENVIRONMENT}}"