ENVIRONMENT: development
SERVER_PORT: 8080
SERVER_NAME: localhost
JAIL_URL: http://jailrunner
JAIL_PATH: /jail
CLIENT_URL: http://client
CLIENT_PATH: /client
CLIENT_STATIC_PATH: /vplclient_static
API_URL: http://api:1337
API_PATH: /apis
MOODLE_URL: http://moodle
MOODLE_PATH: /