kind: ConfigMap
apiVersion: v1
metadata:
  name: jail-config-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
data:
  ENV: {{ENV}}
  API_URL: {{API_URL}}
  API_TOKEN: {{API_TOKEN}}
  JAIL_PORT: "{{JAIL_PORT}}"
  JAIL_SECURE_PORT: "{{JAIL_SECURE_PORT}}"
  {% if HOST_FILE is defined %}
  HOST_FILE: "{{HOST_FILE}}"
  {% endif %}
  {% if CACERT is defined %}
  CACERT: "{{CACERT}}"
  {% endif %}
