apiVersion: v1
kind: Service
metadata:
  name: jail-service-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  ports:
    - name: "8000"
      port: 8000
      protocol: TCP
      targetPort: 80
    - name: "9000"
      port: 9000
      protocol: TCP
      targetPort: 443
  selector:
    app: jail
  type: LoadBalancer
