apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway-deployment-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: alphonse92/vpl_gateway:latest
          name: gateway
          volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
          envFrom:
            - configMapRef:
                name: gateway-config-{{ENVIRONMENT}}
          ports:
            - containerPort: 80
              name: gateway
      volumes:
      - name: secrets
        secret:
          secretName: certificates

