apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
  name: quotes
spec:
  ports:
  - name: "1337"
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: quotes
  type: ClusterIP