apiVersion: v1
kind: Service
metadata:
  name: mysql-{{ENVIRONMENT}}
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app:  mysql-{{ENVIRONMENT}}
  clusterIP: ClusterIP