apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
