apiVersion: v1
kind: Service
metadata:
  name: mongo-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app:  mongo-{{ENVIRONMENT}}
  type: LoadBalancer