kind: ConfigMap
apiVersion: v1
metadata:
  name: api-config-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
data:
  NODE_PATH: {{NODE_PATH}}
  HOST: {{HOST}}
  PORT: "{{PORT}}"
  NODE_ENV: {{NODE_ENV}}
  SYSTEM_CORES: "{{SYSTEM_CORES}}"
  MONGO: {{MONGO}}
  MYSQL: {{MYSQL}}
  MOODLE_HOST: {{MOODLE_HOST}}
  MOODLE_PORT: "{{MOODLE_PORT}}"
  MOODLE_DB_PREFIX: {{MOODLE_DB_PREFIX}}
  MOODLE_AUTH_TYPE: {{MOODLE_AUTH_TYPE}}
  GOOGLE_CLIENT_ID: {{GOOGLE_CLIENT_ID}}
  INIT_USER_TYPE: {{INIT_USER_TYPE}}
  TOKEN_SECRET: {{TOKEN_SECRET}}
  TOKEN_EXP_MINUTES: {{TOKEN_EXP_MINUTES}}
  CACHE_FOLDER: {{CACHE_FOLDER}}
  SHOW_CONFIG_AT_STARTUP: "{{SHOW_CONFIG_AT_STARTUP}}"
  OPEN_DEVELOPMENT_ENDPOINT: "{{OPEN_DEVELOPMENT_ENDPOINT}}"
  PUBLIC: {{PUBLIC}}