apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-deployment-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: alphonse92/vpl_api:latest
          name: api
          envFrom:
            - configMapRef:
                name: api-config-{{ENVIRONMENT}}
          ports:
            - containerPort: 1337
              name: api
