apiVersion: v1
kind: Service
metadata:
  name: api-service-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  ports:
    - name: "1337"
      port: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    app: api
  type: LoadBalancer
