kind: ConfigMap
apiVersion: v1
metadata:
  name: moodle-config-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
data:
  DB_CONNECTOR: {{DB_CONNECTOR}}
  DB_HOST: {{DB_HOST}}
  DB_PORT: "{{DB_PORT}}"
  DB_NAME: {{DB_NAME}}
  DB_USERNAME: {{DB_USERNAME}}
  DB_PASSWORD: {{DB_PASSWORD}}
  DB_PREFIX: {{DB_PREFIX}}
  MOODLE_URL: {{MOODLE_URL}}
  MOODLE_DATA: {{MOODLE_DATA}}
  REVERSE_PROXY: "{{REVERSE_PROXY}}"
  SSL_PROXY: "{{SSL_PROXY}}"
  {% if CACERT is defined %}
  CACERT: "{{CACERT}}"
  {% endif %}