apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv-{{ENVIRONMENT}}
  labels:
    type: local
  namespace: {{ENVIRONMENT}}
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/moodle-{{ENVIRONMENT}}/moodle/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-data-pv-{{ENVIRONMENT}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/moodle-{{ENVIRONMENT}}/moodle_data"
