apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pv-claim-{{ENVIRONMENT}}-moodle
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pv-claim-{{ENVIRONMENT}}-moodle_data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
