apiVersion: v1
kind: Service
metadata:
  name: moodle-{{ENVIRONMENT}}
  namespace: {{ENVIRONMENT}}
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:  moodle-{{ENVIRONMENT}}
  type: LoadBalancer