apiVersion: v1
kind: Service
metadata:
  name: moodle-service-{{ENVIRONMENT}}
  namespace: "{{ENVIRONMENT}}"
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: moodle
  type: LoadBalancer
