 

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * GUI para realizar calculos con fracciones.
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
public class DesktopGUIFraccionario  extends javax.swing.JFrame {

    private Fraccionario fraccionario1;
    private Fraccionario fraccionario2;
    private Fraccionario fraccionario3;

    /**
     * Constructor
     *
     * @param fraccionario1
     * @param fraccionario2
     * @param fraccionario3
     */
    public DesktopGUIFraccionario (Fraccionario fraccionario1, Fraccionario fraccionario2, Fraccionario fraccionario3) {
        initComponents();
        this.fraccionario1 = fraccionario1;
        this.fraccionario2 = fraccionario2;
        this.fraccionario3 = fraccionario3;
        center();
        actualizarGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        cmdLimpiarDatos = new javax.swing.JButton();
        cmdSumar = new javax.swing.JButton();
        cmdRestar = new javax.swing.JButton();
        cmdMultiplicar = new javax.swing.JButton();
        cmdDividir = new javax.swing.JButton();
        panelAdorno = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        panelFraccionario1 = new javax.swing.JPanel();
        lblNumerador1 = new javax.swing.JLabel();
        txtNumerador1 = new javax.swing.JTextField();
        lblDenominador1 = new javax.swing.JLabel();
        txtDenominador1 = new javax.swing.JTextField();
        lblSimplificar1 = new javax.swing.JLabel();
        chkSimplificar1 = new javax.swing.JCheckBox();
        panelFraccionario2 = new javax.swing.JPanel();
        lblNumerador2 = new javax.swing.JLabel();
        txtNumerador2 = new javax.swing.JTextField();
        lblDenominador2 = new javax.swing.JLabel();
        txtDenominador2 = new javax.swing.JTextField();
        lblSimplificar2 = new javax.swing.JLabel();
        chkSimplificar2 = new javax.swing.JCheckBox();
        panelFraccionario3 = new javax.swing.JPanel();
        lblNumerador3 = new javax.swing.JLabel();
        txtNumerador3 = new javax.swing.JTextField();
        lblDenominador3 = new javax.swing.JLabel();
        txtDenominador3 = new javax.swing.JTextField();
        lblSimplificar3 = new javax.swing.JLabel();
        chkSimplificar3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Fraccionarios");
        setResizable(false);

        panelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitulo.setText("Calculadora de Fraccionarios");
        panelTitulo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelBotones.setLayout(new java.awt.GridLayout(1, 5));

        cmdLimpiarDatos.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cmdLimpiarDatos.setText("Limpiar Datos");
        cmdLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarDatosActionPerformed(evt);
            }
        });
        panelBotones.add(cmdLimpiarDatos);

        cmdSumar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cmdSumar.setText("Sumar");
        cmdSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumarActionPerformed(evt);
            }
        });
        panelBotones.add(cmdSumar);

        cmdRestar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cmdRestar.setText("Restar");
        cmdRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestarActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRestar);

        cmdMultiplicar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cmdMultiplicar.setText("Multiplicar");
        cmdMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMultiplicarActionPerformed(evt);
            }
        });
        panelBotones.add(cmdMultiplicar);

        cmdDividir.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cmdDividir.setText("Dividir");
        cmdDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDividirActionPerformed(evt);
            }
        });
        panelBotones.add(cmdDividir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH);

        panelAdorno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelAdorno.setLayout(new java.awt.BorderLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("pi_large.jpg"))); // NOI18N
        panelAdorno.add(lblImagen, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelAdorno, java.awt.BorderLayout.EAST);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelDatos.setLayout(new java.awt.GridLayout(3, 1));

        panelFraccionario1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fraccionario 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 13))); // NOI18N
        panelFraccionario1.setLayout(new java.awt.GridLayout(3, 2));

        lblNumerador1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblNumerador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumerador1.setText("Numerador:");
        panelFraccionario1.add(lblNumerador1);

        txtNumerador1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtNumerador1.setForeground(new java.awt.Color(0, 0, 255));
        txtNumerador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumerador1.setText("0");
        txtNumerador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumerador1FocusLost(evt);
            }
        });
        panelFraccionario1.add(txtNumerador1);

        lblDenominador1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblDenominador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominador1.setText("Denominador:");
        panelFraccionario1.add(lblDenominador1);

        txtDenominador1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtDenominador1.setForeground(new java.awt.Color(0, 0, 255));
        txtDenominador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDenominador1.setText("0");
        txtDenominador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDenominador1FocusLost(evt);
            }
        });
        panelFraccionario1.add(txtDenominador1);

        lblSimplificar1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblSimplificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimplificar1.setText("Simplificar:");
        panelFraccionario1.add(lblSimplificar1);

        chkSimplificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkSimplificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSimplificar1ActionPerformed(evt);
            }
        });
        panelFraccionario1.add(chkSimplificar1);

        panelDatos.add(panelFraccionario1);
        panelFraccionario1.getAccessibleContext().setAccessibleDescription("");

        panelFraccionario2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fraccionario2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 13))); // NOI18N
        panelFraccionario2.setLayout(new java.awt.GridLayout(3, 2));

        lblNumerador2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblNumerador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumerador2.setText("Numerador:");
        panelFraccionario2.add(lblNumerador2);

        txtNumerador2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtNumerador2.setForeground(new java.awt.Color(0, 0, 255));
        txtNumerador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumerador2.setText("0");
        txtNumerador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumerador2FocusLost(evt);
            }
        });
        panelFraccionario2.add(txtNumerador2);

        lblDenominador2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblDenominador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominador2.setText("Denominador:");
        panelFraccionario2.add(lblDenominador2);

        txtDenominador2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtDenominador2.setForeground(new java.awt.Color(0, 0, 255));
        txtDenominador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDenominador2.setText("0");
        txtDenominador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDenominador2FocusLost(evt);
            }
        });
        panelFraccionario2.add(txtDenominador2);

        lblSimplificar2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblSimplificar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimplificar2.setText("Simplificar:");
        panelFraccionario2.add(lblSimplificar2);

        chkSimplificar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkSimplificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSimplificar2ActionPerformed(evt);
            }
        });
        panelFraccionario2.add(chkSimplificar2);

        panelDatos.add(panelFraccionario2);

        panelFraccionario3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fraccionario Resultante:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 13))); // NOI18N
        panelFraccionario3.setLayout(new java.awt.GridLayout(3, 2));

        lblNumerador3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblNumerador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumerador3.setText("Numerador:");
        panelFraccionario3.add(lblNumerador3);

        txtNumerador3.setEditable(false);
        txtNumerador3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtNumerador3.setForeground(new java.awt.Color(0, 0, 255));
        txtNumerador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumerador3.setText("0");
        panelFraccionario3.add(txtNumerador3);

        lblDenominador3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblDenominador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominador3.setText("Denominador:");
        panelFraccionario3.add(lblDenominador3);

        txtDenominador3.setEditable(false);
        txtDenominador3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtDenominador3.setForeground(new java.awt.Color(0, 0, 255));
        txtDenominador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDenominador3.setText("0");
        panelFraccionario3.add(txtDenominador3);

        lblSimplificar3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblSimplificar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSimplificar3.setText("Simplificar:");
        panelFraccionario3.add(lblSimplificar3);

        chkSimplificar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkSimplificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSimplificar3ActionPerformed(evt);
            }
        });
        panelFraccionario3.add(chkSimplificar3);

        panelDatos.add(panelFraccionario3);

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarDatosActionPerformed
        this.fraccionario1.setNumerador(0);
        this.fraccionario1.setDenominador(1);
        this.fraccionario2.setNumerador(0);
        this.fraccionario2.setDenominador(1);
        this.fraccionario3.setNumerador(0);
        this.fraccionario3.setDenominador(1);
        chkSimplificar1.setSelected(false);
        chkSimplificar2.setSelected(false);
        actualizarGUI();
        JOptionPane.showMessageDialog(this, "Se limpiaron los Datos...", "Se limpiaron los Datos...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdLimpiarDatosActionPerformed

    private void cmdSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumarActionPerformed
        fraccionario3 = fraccionario1.sumar(fraccionario2);
        if (chkSimplificar3.isSelected()) {
            this.fraccionario3.simplificar();
        }
        this.actualizarGUI();
    }//GEN-LAST:event_cmdSumarActionPerformed

    private void cmdRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestarActionPerformed
        fraccionario3 = fraccionario1.restar(fraccionario2);
        if (chkSimplificar3.isSelected()) {
            this.fraccionario3.simplificar();
        }
        this.actualizarGUI();
    }//GEN-LAST:event_cmdRestarActionPerformed

    private void cmdMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMultiplicarActionPerformed
        fraccionario3 = fraccionario1.multiplicar(fraccionario2);
        if (chkSimplificar3.isSelected()) {
            this.fraccionario3.simplificar();
        }
        this.actualizarGUI();
    }//GEN-LAST:event_cmdMultiplicarActionPerformed

    private void cmdDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDividirActionPerformed
        fraccionario3 = fraccionario1.dividir(fraccionario2);
        if (chkSimplificar3.isSelected()) {
            this.fraccionario3.simplificar();
        }
        this.actualizarGUI();
    }//GEN-LAST:event_cmdDividirActionPerformed

    private void chkSimplificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSimplificar1ActionPerformed
        if (chkSimplificar1.isSelected()) {
            this.fraccionario1.setNumerador(Integer.parseInt(this.txtNumerador1.getText()));
            this.fraccionario1.setDenominador(Integer.parseInt(this.txtDenominador1.getText()));
            this.fraccionario1.simplificar();
            actualizarGUI();
        }
    }//GEN-LAST:event_chkSimplificar1ActionPerformed

    private void chkSimplificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSimplificar2ActionPerformed
        if (chkSimplificar2.isSelected()) {
            this.fraccionario2.setNumerador(Integer.parseInt(this.txtNumerador2.getText()));
            this.fraccionario2.setDenominador(Integer.parseInt(this.txtDenominador2.getText()));
            this.fraccionario2.simplificar();
            actualizarGUI();
        }
    }//GEN-LAST:event_chkSimplificar2ActionPerformed

    private void chkSimplificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSimplificar3ActionPerformed
        if (chkSimplificar3.isSelected()) {
            this.fraccionario3.simplificar();
            actualizarGUI();
        }
    }//GEN-LAST:event_chkSimplificar3ActionPerformed
    
    private void txtNumerador1FocusLost(java.awt.event.FocusEvent evt) {                                        
      fraccionario1.setNumerador(Integer.parseInt(txtNumerador1.getText()));
    }
    
    private void txtNumerador2FocusLost(java.awt.event.FocusEvent evt) {                                        
      fraccionario2.setNumerador(Integer.parseInt(txtNumerador2.getText()));
    }
    
    private void txtDenominador1FocusLost(java.awt.event.FocusEvent evt) {                                        
      fraccionario1.setDenominador(Integer.parseInt(txtDenominador1.getText()));
    }
    
    private void txtDenominador2FocusLost(java.awt.event.FocusEvent evt) {                                        
      fraccionario2.setDenominador(Integer.parseInt(txtDenominador2.getText()));
    }

    private void actualizarGUI() {
        this.txtNumerador1.setText(String.valueOf(fraccionario1.getNumerador()));
        this.txtNumerador2.setText(String.valueOf(fraccionario2.getNumerador()));
        this.txtNumerador3.setText(String.valueOf(fraccionario3.getNumerador()));
        this.txtDenominador1.setText(String.valueOf(fraccionario1.getDenominador()));
        this.txtDenominador2.setText(String.valueOf(fraccionario2.getDenominador()));
        this.txtDenominador3.setText(String.valueOf(fraccionario3.getDenominador()));
    }//fin actualizarGUI

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSimplificar1;
    private javax.swing.JCheckBox chkSimplificar2;
    private javax.swing.JCheckBox chkSimplificar3;
    private javax.swing.JButton cmdLimpiarDatos;
    private javax.swing.JButton cmdDividir;
    private javax.swing.JButton cmdMultiplicar;
    private javax.swing.JButton cmdRestar;
    private javax.swing.JButton cmdSumar;
    private javax.swing.JLabel lblDenominador1;
    private javax.swing.JLabel lblDenominador2;
    private javax.swing.JLabel lblDenominador3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNumerador1;
    private javax.swing.JLabel lblNumerador2;
    private javax.swing.JLabel lblNumerador3;
    private javax.swing.JLabel lblSimplificar1;
    private javax.swing.JLabel lblSimplificar2;
    private javax.swing.JLabel lblSimplificar3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelAdorno;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelFraccionario1;
    private javax.swing.JPanel panelFraccionario2;
    private javax.swing.JPanel panelFraccionario3;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    // End of variables declaration//GEN-END:variables

    private void center() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
}
